### ISSUE TITLE
[BUG] Pressing Up in REPL Locks One into Normal Mode

### ISSUE THREAD

**Issue by TheCedarPrince** [caleb-allen/VimBindings.jl#18] opened 2022-09-10 20:07 UTC
When I press up in the Julia REPL for autocompletion, I am stuck in normal mode and cannot swap into insert mode to edit an entry. The only way to get out of this locking behavior is to press enter to execute the command I navigated back to in the REPL history. Anyway this could be fixed? Thanks!

**Comment by caleb-allen** [comment] 2022-09-10 21:07
Thanks for the report!

What Julia version are you using?

I will take a look at this soon.

**Comment by caleb-allen** [comment] 2022-09-23 17:14
@TheCedarPrince are you still encountering this issue with the most recent code? You may need to uninstall and reinstall the package to check (this will be a lot easier once I've put this on the package registry, which I'd like to do soon..)


A note about the possible cause:

I believe the root cause of this is related to the `log` function, which grabs a handle to a local socket when it's available, used for logging and debugging.

https://github.com/caleb-allen/VimBindings.jl/blob/248645a92a03eccdbaf9249a75262ae935a72a90/src/VimBindings.jl#L421-L435

I think the "lockup" is due to the to the call to `connect` hanging when the socket isn't open. It would also throw an invisible error if the `Sockets` package were missing, which was the case after I recently removed some dependencies.

**Comment by caleb-allen** [comment] 2022-10-18 14:40
I think the lockup could also be due to the escape sequence used when hitting the up key. I seem to get freezes when I use the up key, but not when I use `k` to navigate up in history.

**Comment by MilesCranmer** [comment] 2022-11-02 23:03
Seeing this on Julia 1.8.2 as well. If it's any use, I was not able to exit even with ctrl-c or ctrl-\; it seemed to completely lock the terminal.

**Comment by caleb-allen** [comment] 2022-11-07 07:57
@MilesCranmer can you confirm that this behavior is present when VimBindings it loaded from the terminal, like `julia -i -e ”using VimBindings"`? This as opposed to loading it in `startup.jl`

**Comment by caleb-allen** [comment] 2022-11-07 08:17
Also, if you encounter it again, try using the escape key and then see if that unlocks the repl

**Comment by MilesCranmer** [comment] 2022-11-07 09:32
Confirmed that I loaded `VimBindings.jl` from the terminal at startup. I tried pushing the escape key but it did not unlock it unfortunately.

**Comment by caleb-allen** [comment] 2022-11-07 11:42
@MilesCranmer thank you for checking, I'll see what I can do to resolve this

**Comment by MilesCranmer** [comment] 2023-01-10 13:40
I see this much less now which is great, although sometimes it still comes up. I wonder if it might be good to have a fail-safe in whatever loop it gets stuck in, so it throws an error after `n` iterations rather than locks up?

**Comment by MilesCranmer** [comment] 2023-01-10 13:44
To help debug this - I can reproducibly get stuck in this loop when I have a symbol object, let's say `t=Symbol("/Users/mcranmer/.julia/packages/Static/Ldb7F/src/Static.jl")`, write `t` at the command prompt, and then enter normal mode, and try to hit `<tab>` (by accident). It seems to get stuck at that point.

**Comment by caleb-allen** [comment] 2023-01-12 13:55
@MilesCranmer what OS + terminal are you using?

I'm unable to reproduce the freeze using the steps you provided from my machine running Manjaro Linux with `alacritty` terminal. The fact that it's reliably triggered by an erroneous `<tab>` makes me suspect that it is the handling of keys with escape sequences, which may very well differ by OS.

**Comment by MilesCranmer** [comment] 2023-01-12 19:03
Sorry, my MWE turns out to not actually be a MWE at all. The above example actually works fine, as you observed

However, the following very specific setup seems to break things:

1. Launch tmux. (works fine outside tmux)
2. Open julia with VimBindings, version 1.9.0-beta2 of Julia (works fine with 1.8.5), and version 0.2.1 of VimBindings.jl
3. Run the following code (after installing SnoopCompile.jl and SymbolicRegression.jl)

```julia
using SnoopCompile
invalidations = @snoopr begin
    using SymbolicRegression
end
trees = invalidation_trees(invalidations)
t = trees[1]
```

4. Now, type `t.method.file` at the command prompt.
5. Enter normal mode, and move the cursor to right after the end, i.e., `file|`.
6. Hit `<tab>`. The REPL will be locked.

I tried to minimize this down into a MWE but I didn't actually verify it.

It turns out that every step of this seems to be necessary to get the lock; I'm not sure how I can reproduce it with a smaller example. It's very strange that each part of this is required. I'll keep using VimBindings.jl and see if there are any other simpler situations that pop up.

I'm on macOS 13.1, running in iTerm2, zsh 5.8.1, tmux 3.3a.

**Comment by caleb-allen** [comment] 2023-01-12 20:10
@MilesCranmer very strange indeed. I'll try to reproduce the freeze you're seeing.

Do you happen to have the `escape-time` value set in your `~/.tmux.conf`?

**Comment by MilesCranmer** [comment] 2023-01-12 20:28
I have `set -g escape-time 0` in my `.tmux.conf`. In all honesty I can't remember what I set that for... Could that be the reason for this?

**Comment by MilesCranmer** [comment] 2023-01-12 20:29
Okay, I set `set -g escape-time 1`, and now the error goes away. Very weird.

**Comment by caleb-allen** [comment] 2023-01-12 21:33
> Could that be the reason for this?

@MilesCranmer It very well may be. The reason is that many special keys (arrow keys, etc) are encoded as `Esc` + `x` where x is specific to the special key.

The problem is that the `Esc` key simply sends `Esc` and nothing more. This creates ambiguity - was the `Esc` key struck, or is it the beginning of a longer escape sequence?

The solution is to wait a very short period to see if other keys come in quickly. If so, interpret the keys as a special escape sequence. If no more keys arrive, assume that the `Esc` key was struck. As an aside, this problem is actually the reason VimBindings must be loaded so early, since a decent amount of REPL code is overwritten to hacks how escape sequences are interpreted so that the `Esc` key can be used.

Regardless, tmux uses the `escape-time` setting to determine how long to wait after receiving an `Esc` before making the above decision. By default this is set to 500ms, presumably to work well over spotty ssh sessions, although this is noticeably high and users often reduce this.

My guess is that setting `escape-time` to 0 resulted in a race condition of some kind, where tmux passed (and maybe modified) the escape codes before being able to confirm what type of `Esc` was being used.

If you continue to see issues like this you may try to increase `escape-time` to 10 just to be safe. 

Also, VimBindings should be able to handle scenarios like this without simply locking. So I'll keep this issue open.

**Comment by MilesCranmer** [comment] 2023-01-12 21:35
Thanks for the detailed explanation! I'll indeed bump up the escape time a bit.

**Comment by caleb-allen** [comment] 2023-05-27 00:01
@MilesCranmer @TheCedarPrince are you still seeing this freezing behavior on 0.3.2+? 

My understanding is that the freezing behavior is resolved so I'm going to close this issue.

Please re-open if you still experience this

**Closed** 2023-05-27 00:03 UTC
Labels: bug
